/**
 * Factbook 資源/農産物/産業リストの日本語用語辞書（termsZh.ts と同じキー）。
 * 辞書にない語は英語原文のまま表示する。
 */
export const DICT_JA: Record<string, string> = {
  // ---- 鉱物・エネルギー ----
  'coal': '石炭', 'iron ore': '鉄鉱石', 'petroleum': '石油', 'crude petroleum': '原油',
  'refined petroleum': '石油製品', 'oil': '石油', 'crude oil': '原油', 'natural gas': '天然ガス',
  'gold': '金', 'silver': '銀', 'copper': '銅', 'uranium': 'ウラン', 'bauxite': 'ボーキサイト',
  'alumina': 'アルミナ', 'aluminum': 'アルミニウム', 'aluminium': 'アルミニウム', 'timber': '木材', 'lumber': '製材',
  'hydropower': '水力', 'hydropower potential': '水力資源', 'hydroelectric power': '水力発電',
  'rare earth elements': 'レアアース', 'rare earths': 'レアアース', 'tungsten': 'タングステン', 'antimony': 'アンチモン',
  'manganese': 'マンガン', 'magnetite': '磁鉄鉱', 'molybdenum': 'モリブデン', 'vanadium': 'バナジウム', 'zinc': '亜鉛',
  'lead': '鉛', 'tin': 'スズ', 'nickel': 'ニッケル', 'phosphates': 'リン鉱石', 'phosphate rock': 'リン鉱石',
  'potash': 'カリ塩', 'salt': '塩', 'sulfur': '硫黄', 'graphite': '黒鉛', 'chromium': 'クロム',
  'chromite': 'クロム鉄鉱', 'cobalt': 'コバルト', 'lithium': 'リチウム', 'mercury': '水銀', 'asbestos': '石綿',
  'limestone': '石灰岩', 'marble': '大理石', 'granite': '花崗岩', 'gypsum': '石膏',
  'clay': '粘土', 'kaolin': 'カオリン', 'sand': '砂', 'gravel': '砂利', 'stone': '石材',
  'diamonds': 'ダイヤモンド', 'gemstones': '宝石', 'precious stones': '宝石', 'platinum': 'プラチナ',
  'palladium': 'パラジウム', 'titanium': 'チタン', 'zirconium': 'ジルコニウム', 'silica': 'シリカ', 'quartz': '石英',
  'feldspar': '長石', 'mica': '雲母', 'barite': '重晶石', 'boron': 'ホウ素', 'bromine': '臭素',
  'magnesium': 'マグネシウム', 'soda ash': 'ソーダ灰', 'peat': '泥炭', 'geothermal power': '地熱',
  'geothermal energy': '地熱エネルギー', 'solar power': '太陽光', 'solar': '太陽光', 'wind power': '風力',
  'wind': '風力', 'helium': 'ヘリウム', 'arsenic': 'ヒ素', 'bismuth': 'ビスマス', 'cadmium': 'カドミウム',
  'ferrosilicon': 'フェロシリコン', 'gallium': 'ガリウム', 'germanium': 'ゲルマニウム', 'hafnium': 'ハフニウム', 'indium': 'インジウム',
  'niobium': 'ニオブ', 'tantalum': 'タンタル', 'tellurium': 'テルル', 'selenium': 'セレン', 'strontium': 'ストロンチウム',
  'rhenium': 'レニウム', 'beryllium': 'ベリリウム', 'fluorspar': '蛍石', 'talc': 'タルク', 'dolomite': 'ドロマイト',
  'pumice': '軽石', 'perlite': 'パーライト', 'shale oil': 'シェールオイル', 'oil shale': 'オイルシェール',
  'tar sands': 'オイルサンド', 'forests': '森林', 'forest': '森林', 'wildlife': '野生生物',
  'pastures': '牧草地', 'pastureland': '牧草地', 'grazing land': '放牧地', 'farmland': '農地',
  'water': '水資源', 'freshwater': '淡水', 'fish': '魚類', 'fisheries': '水産資源',
  'arable land': '耕作地', 'fertile soil': '肥沃な土壌', 'fertile soils': '肥沃な土壌', 'iron': '鉄',
  'steel': '鉄鋼', 'iron and steel': '鉄鋼', 'scrap iron': 'くず鉄',
  // ---- 農産物 ----
  'maize': 'トウモロコシ', 'corn': 'トウモロコシ', 'rice': '米', 'wheat': '小麦', 'vegetables': '野菜',
  'sugarcane': 'サトウキビ', 'sugar cane': 'サトウキビ', 'sugar beets': 'テンサイ', 'sugar beet': 'テンサイ',
  'sugar': '砂糖', 'potatoes': 'ジャガイモ', 'sweet potatoes': 'サツマイモ', 'cassava': 'キャッサバ',
  'soybeans': '大豆', 'soybean': '大豆', 'barley': '大麦', 'oats': 'オーツ麦', 'rye': 'ライ麦',
  'sorghum': 'ソルガム', 'millet': 'キビ', 'cotton': '綿花', 'seed cotton': '実綿',
  'tobacco': 'タバコ', 'tea': '茶', 'coffee': 'コーヒー', 'cocoa': 'カカオ', 'cocoa beans': 'カカオ豆',
  'bananas': 'バナナ', 'plantains': 'プランテン', 'oranges': 'オレンジ', 'tangerines': 'ミカン',
  'apples': 'リンゴ', 'grapes': 'ブドウ', 'olives': 'オリーブ', 'olive oil': 'オリーブオイル',
  'palm oil': 'パーム油', 'oil palm fruit': 'アブラヤシの実', 'coconuts': 'ココナッツ', 'copra': 'コプラ',
  'rubber': 'ゴム', 'natural rubber': '天然ゴム', 'groundnuts': '落花生', 'peanuts': '落花生',
  'sunflower seeds': 'ヒマワリの種', 'sunflower seed': 'ヒマワリの種', 'rapeseed': '菜種',
  'sesame': 'ゴマ', 'sesame seeds': 'ゴマ', 'dates': 'ナツメヤシ', 'figs': 'イチジク',
  'tomatoes': 'トマト', 'onions': 'タマネギ', 'cucumbers': 'キュウリ', 'cucumbers/gherkins': 'キュウリ',
  'watermelons': 'スイカ', 'melons': 'メロン', 'cantaloupes': 'カンタロープ', 'mangoes': 'マンゴー',
  'mangoes/guavas': 'マンゴー/グアバ', 'pineapples': 'パイナップル', 'papayas': 'パパイヤ',
  'avocados': 'アボカド', 'cabbages': 'キャベツ', 'carrots': 'ニンジン', 'carrots/turnips': 'ニンジン/カブ',
  'chillies/peppers': 'トウガラシ', 'peppers': 'トウガラシ', 'garlic': 'ニンニク', 'ginger': 'ショウガ',
  'beans': '豆類', 'green beans': 'サヤインゲン', 'chickpeas': 'ヒヨコ豆', 'chick peas': 'ヒヨコ豆',
  'lentils': 'レンズ豆', 'peas': 'エンドウ豆', 'yams': 'ヤムイモ', 'taro': 'タロイモ', 'plantain': 'プランテン',
  'milk': '牛乳', 'eggs': '鶏卵', 'beef': '牛肉', 'pork': '豚肉', 'poultry': '家禽肉',
  'chicken': '鶏肉', 'mutton': '羊肉', 'lamb': '子羊肉', 'goat': 'ヤギ', 'goat meat': 'ヤギ肉',
  'goat milk': 'ヤギ乳', 'sheep milk': '羊乳', 'camel milk': 'ラクダ乳', 'camel meat': 'ラクダ肉',
  'buffalo milk': '水牛乳', 'wool': '羊毛', 'honey': '蜂蜜', 'fruit': '果物', 'fruits': '果物',
  'citrus': '柑橘類', 'citrus fruit': '柑橘類', 'grain': '穀物', 'cereals': '穀物',
  'livestock': '畜産', 'cattle': '牛', 'sheep': '羊', 'pigs': '豚', 'dairy products': '乳製品',
  'dairy': '乳製品', 'shrimp': 'エビ', 'prawns': 'クルマエビ', 'seafood': '水産物', 'nuts': 'ナッツ',
  'almonds': 'アーモンド', 'pistachios': 'ピスタチオ', 'hazelnuts': 'ヘーゼルナッツ', 'walnuts': 'クルミ',
  'cashews': 'カシューナッツ', 'cashew nuts': 'カシューナッツ', 'cloves': 'クローブ', 'vanilla': 'バニラ',
  'spices': '香辛料', 'tropical fruit': '熱帯果実', 'other meats': 'その他の肉類', 'meat': '食肉',
  'pulses': '豆類', 'jute': 'ジュート', 'flax': '亜麻', 'silk': '生糸', 'hides': '皮革',
  'skins': '毛皮', 'flowers': '花卉', 'cut flowers': '切り花', 'oilseeds': '油糧種子',
  'apricots': 'アンズ', 'peaches': 'モモ', 'peaches/nectarines': 'モモ/ネクタリン', 'pears': 'ナシ',
  'plums': 'スモモ', 'cherries': 'サクランボ', 'strawberries': 'イチゴ', 'blueberries': 'ブルーベリー',
  'lemons': 'レモン', 'lemons/limes': 'レモン/ライム', 'grapefruit': 'グレープフルーツ', 'kiwifruit': 'キウイフルーツ',
  'quinoa': 'キヌア', 'triticale': 'ライコムギ', 'buckwheat': 'ソバ', 'mushrooms': 'キノコ',
  'mushrooms/truffles': 'キノコ/トリュフ', 'hops': 'ホップ', 'wine': 'ワイン', 'beer': 'ビール',
  // ---- 産業 ----
  'mining': '鉱業', 'machinery': '機械', 'textiles': '繊維', 'apparel': 'アパレル',
  'clothing': '衣料', 'garments': '衣料品', 'food processing': '食品加工', 'food products': '食品',
  'processed food': '加工食品', 'chemicals': '化学', 'chemical products': '化学製品',
  'fertilizers': '肥料', 'fertilizer': '肥料', 'cement': 'セメント', 'electronics': '電子機器',
  'consumer electronics': '家電', 'automobiles': '自動車', 'motor vehicles': '自動車',
  'cars': '乗用車', 'vehicles': '車両', 'auto parts': '自動車部品', 'vehicle parts': '自動車部品',
  'shipbuilding': '造船', 'aircraft': '航空機', 'aerospace': '航空宇宙',
  'telecommunications': '電気通信', 'telecommunications equipment': '通信機器',
  'petroleum refining': '石油精製', 'oil refining': '石油精製', 'petrochemicals': '石油化学',
  'pharmaceuticals': '医薬品', 'medicaments': '医薬品', 'packaged medicines': '包装医薬品',
  'tourism': '観光業', 'banking': '銀行業', 'finance': '金融', 'financial services': '金融サービス',
  'insurance': '保険', 'construction': '建設', 'paper': '製紙', 'paper products': '紙製品',
  'pulp': 'パルプ', 'wood products': '木製品', 'wood': '木材', 'furniture': '家具',
  'toys': '玩具', 'footwear': '履物', 'shoes': '靴', 'leather': '皮革',
  'leather goods': '革製品', 'glass': 'ガラス', 'ceramics': '陶磁器', 'rubber products': 'ゴム製品',
  'plastics': 'プラスチック', 'plastic products': 'プラスチック製品', 'sugar processing': '製糖',
  'sugar refining': '製糖', 'brewing': '醸造', 'distilling': '蒸留酒製造', 'beverages': '飲料',
  'tobacco products': 'タバコ製品', 'fishing': '漁業', 'fish processing': '水産加工',
  'forestry': '林業', 'agriculture': '農業', 'energy': 'エネルギー', 'electricity': '電力',
  'software': 'ソフトウェア', 'information technology': '情報技術', 'semiconductors': '半導体',
  'integrated circuits': '集積回路', 'machine building': '機械製造', 'metallurgy': '冶金',
  'metals': '金属', 'metal products': '金属製品', 'coal mining': '石炭採掘',
  'light industry': '軽工業', 'handicrafts': '手工芸品', 'carpets': 'じゅうたん',
  'transport equipment': '輸送機器', 'transportation equipment': '輸送機器',
  'shipping': '海運', 'offshore financial services': 'オフショア金融', 'real estate': '不動産',
  'defense products': '防衛装備品', 'arms': '武器', 'weapons': '武器', 'satellites': '人工衛星',
  'computers': 'コンピュータ', 'broadcasting equipment': '放送機器', 'office machinery': '事務機器',
  'gas turbines': 'ガスタービン', 'ships': '船舶', 'boats': '小型船舶', 'trucks': 'トラック',
  'motorcycles': 'オートバイ', 'bicycles': '自転車', 'jewelry': '宝飾品', 'watches': '時計',
  'precision instruments': '精密機器', 'optical instruments': '光学機器',
  'medical equipment': '医療機器', 'scientific instruments': '科学機器', 'diamonds cutting': 'ダイヤモンド研磨',
  'diamond cutting': 'ダイヤモンド研磨', 'gas': '天然ガス', 'liquefied natural gas': '液化天然ガス',
  'aluminum products': 'アルミ製品', 'copper products': '銅製品', 'gold mining': '金採掘',
  'soap': '石鹸', 'cigarettes': 'たばこ', 'flour': '小麦粉', 'flour milling': '製粉',
  'palm kernels': 'パーム核', 'cotton yarn': '綿糸', 'cotton lint': '繰綿',
  'crude oil production': '原油生産', 'oil production': '石油生産',
  'basic petrochemicals': '基礎石油化学製品', 'ammonia': 'アンモニア', 'industrial gases': '産業ガス',
  'sodium hydroxide (caustic soda)': '苛性ソーダ', 'caustic soda': '苛性ソーダ',
  'commercial ship repair': '商船修理', 'commercial aircraft repair': '民間航空機整備',
  'natural gas production': '天然ガス生産', 'phosphate mining': 'リン鉱石採掘',
  'aluminum smelting': 'アルミ製錬', 'copper smelting': '銅製錬', 'zinc smelting': '亜鉛製錬',
  'oil refineries': '製油所', 'sawmills': '製材所', 'meat processing': '食肉加工',
  'meat packing': '食肉加工', 'dairy processing': '乳製品加工', 'canning': '缶詰製造',
  'wine making': 'ワイン醸造', 'winemaking': 'ワイン醸造', 'olive oil production': 'オリーブオイル生産',
}
