/**
 * Русский словарь терминов для списков Factbook (ресурсы/сельхозпродукция/отрасли),
 * те же ключи, что в termsZh.ts. Отсутствующие слова остаются на английском.
 */
export const DICT_RU: Record<string, string> = {
  // ---- Полезные ископаемые и энергия ----
  'coal': 'уголь', 'iron ore': 'железная руда', 'petroleum': 'нефть', 'crude petroleum': 'сырая нефть',
  'refined petroleum': 'нефтепродукты', 'oil': 'нефть', 'crude oil': 'сырая нефть', 'natural gas': 'природный газ',
  'gold': 'золото', 'silver': 'серебро', 'copper': 'медь', 'uranium': 'уран', 'bauxite': 'бокситы',
  'alumina': 'глинозём', 'aluminum': 'алюминий', 'aluminium': 'алюминий', 'timber': 'древесина', 'lumber': 'пиломатериалы',
  'hydropower': 'гидроэнергия', 'hydropower potential': 'гидроэнергетический потенциал', 'hydroelectric power': 'гидроэлектроэнергия',
  'rare earth elements': 'редкоземельные элементы', 'rare earths': 'редкоземельные металлы', 'tungsten': 'вольфрам', 'antimony': 'сурьма',
  'manganese': 'марганец', 'magnetite': 'магнетит', 'molybdenum': 'молибден', 'vanadium': 'ванадий', 'zinc': 'цинк',
  'lead': 'свинец', 'tin': 'олово', 'nickel': 'никель', 'phosphates': 'фосфаты', 'phosphate rock': 'фосфориты',
  'potash': 'калийные соли', 'salt': 'соль', 'sulfur': 'сера', 'graphite': 'графит', 'chromium': 'хром',
  'chromite': 'хромит', 'cobalt': 'кобальт', 'lithium': 'литий', 'mercury': 'ртуть', 'asbestos': 'асбест',
  'limestone': 'известняк', 'marble': 'мрамор', 'granite': 'гранит', 'gypsum': 'гипс',
  'clay': 'глина', 'kaolin': 'каолин', 'sand': 'песок', 'gravel': 'гравий', 'stone': 'камень',
  'diamonds': 'алмазы', 'gemstones': 'драгоценные камни', 'precious stones': 'драгоценные камни', 'platinum': 'платина',
  'palladium': 'палладий', 'titanium': 'титан', 'zirconium': 'цирконий', 'silica': 'кремнезём', 'quartz': 'кварц',
  'feldspar': 'полевой шпат', 'mica': 'слюда', 'barite': 'барит', 'boron': 'бор', 'bromine': 'бром',
  'magnesium': 'магний', 'soda ash': 'кальцинированная сода', 'peat': 'торф', 'geothermal power': 'геотермальная энергия',
  'geothermal energy': 'геотермальная энергия', 'solar power': 'солнечная энергия', 'solar': 'солнечная энергия', 'wind power': 'энергия ветра',
  'wind': 'энергия ветра', 'helium': 'гелий', 'arsenic': 'мышьяк', 'bismuth': 'висмут', 'cadmium': 'кадмий',
  'ferrosilicon': 'ферросилиций', 'gallium': 'галлий', 'germanium': 'германий', 'hafnium': 'гафний', 'indium': 'индий',
  'niobium': 'ниобий', 'tantalum': 'тантал', 'tellurium': 'теллур', 'selenium': 'селен', 'strontium': 'стронций',
  'rhenium': 'рений', 'beryllium': 'бериллий', 'fluorspar': 'плавиковый шпат', 'talc': 'тальк', 'dolomite': 'доломит',
  'pumice': 'пемза', 'perlite': 'перлит', 'shale oil': 'сланцевая нефть', 'oil shale': 'горючие сланцы',
  'tar sands': 'битуминозные пески', 'forests': 'леса', 'forest': 'лес', 'wildlife': 'дикая природа',
  'pastures': 'пастбища', 'pastureland': 'пастбища', 'grazing land': 'пастбищные угодья', 'farmland': 'сельхозугодья',
  'water': 'водные ресурсы', 'freshwater': 'пресная вода', 'fish': 'рыба', 'fisheries': 'рыбные ресурсы',
  'arable land': 'пахотные земли', 'fertile soil': 'плодородные почвы', 'fertile soils': 'плодородные почвы', 'iron': 'железо',
  'steel': 'сталь', 'iron and steel': 'чёрная металлургия', 'scrap iron': 'металлолом',
  // ---- Сельхозпродукция ----
  'maize': 'кукуруза', 'corn': 'кукуруза', 'rice': 'рис', 'wheat': 'пшеница', 'vegetables': 'овощи',
  'sugarcane': 'сахарный тростник', 'sugar cane': 'сахарный тростник', 'sugar beets': 'сахарная свёкла', 'sugar beet': 'сахарная свёкла',
  'sugar': 'сахар', 'potatoes': 'картофель', 'sweet potatoes': 'батат', 'cassava': 'маниок',
  'soybeans': 'соя', 'soybean': 'соя', 'barley': 'ячмень', 'oats': 'овёс', 'rye': 'рожь',
  'sorghum': 'сорго', 'millet': 'просо', 'cotton': 'хлопок', 'seed cotton': 'хлопок-сырец',
  'tobacco': 'табак', 'tea': 'чай', 'coffee': 'кофе', 'cocoa': 'какао', 'cocoa beans': 'какао-бобы',
  'bananas': 'бананы', 'plantains': 'плантаны', 'oranges': 'апельсины', 'tangerines': 'мандарины',
  'apples': 'яблоки', 'grapes': 'виноград', 'olives': 'оливки', 'olive oil': 'оливковое масло',
  'palm oil': 'пальмовое масло', 'oil palm fruit': 'плоды масличной пальмы', 'coconuts': 'кокосы', 'copra': 'копра',
  'rubber': 'каучук', 'natural rubber': 'натуральный каучук', 'groundnuts': 'арахис', 'peanuts': 'арахис',
  'sunflower seeds': 'семена подсолнечника', 'sunflower seed': 'семена подсолнечника', 'rapeseed': 'рапс',
  'sesame': 'кунжут', 'sesame seeds': 'кунжут', 'dates': 'финики', 'figs': 'инжир',
  'tomatoes': 'томаты', 'onions': 'лук', 'cucumbers': 'огурцы', 'cucumbers/gherkins': 'огурцы',
  'watermelons': 'арбузы', 'melons': 'дыни', 'cantaloupes': 'канталупы', 'mangoes': 'манго',
  'mangoes/guavas': 'манго/гуава', 'pineapples': 'ананасы', 'papayas': 'папайя',
  'avocados': 'авокадо', 'cabbages': 'капуста', 'carrots': 'морковь', 'carrots/turnips': 'морковь/репа',
  'chillies/peppers': 'перец', 'peppers': 'перец', 'garlic': 'чеснок', 'ginger': 'имбирь',
  'beans': 'фасоль', 'green beans': 'стручковая фасоль', 'chickpeas': 'нут', 'chick peas': 'нут',
  'lentils': 'чечевица', 'peas': 'горох', 'yams': 'ямс', 'taro': 'таро', 'plantain': 'плантан',
  'milk': 'молоко', 'eggs': 'яйца', 'beef': 'говядина', 'pork': 'свинина', 'poultry': 'мясо птицы',
  'chicken': 'курятина', 'mutton': 'баранина', 'lamb': 'ягнятина', 'goat': 'козы', 'goat meat': 'козлятина',
  'goat milk': 'козье молоко', 'sheep milk': 'овечье молоко', 'camel milk': 'верблюжье молоко', 'camel meat': 'верблюжатина',
  'buffalo milk': 'молоко буйволиц', 'wool': 'шерсть', 'honey': 'мёд', 'fruit': 'фрукты', 'fruits': 'фрукты',
  'citrus': 'цитрусовые', 'citrus fruit': 'цитрусовые', 'grain': 'зерно', 'cereals': 'зерновые',
  'livestock': 'животноводство', 'cattle': 'крупный рогатый скот', 'sheep': 'овцы', 'pigs': 'свиньи', 'dairy products': 'молочные продукты',
  'dairy': 'молочные продукты', 'shrimp': 'креветки', 'prawns': 'креветки', 'seafood': 'морепродукты', 'nuts': 'орехи',
  'almonds': 'миндаль', 'pistachios': 'фисташки', 'hazelnuts': 'фундук', 'walnuts': 'грецкие орехи',
  'cashews': 'кешью', 'cashew nuts': 'кешью', 'cloves': 'гвоздика', 'vanilla': 'ваниль',
  'spices': 'пряности', 'tropical fruit': 'тропические фрукты', 'other meats': 'прочее мясо', 'meat': 'мясо',
  'pulses': 'бобовые', 'jute': 'джут', 'flax': 'лён', 'silk': 'шёлк', 'hides': 'шкуры',
  'skins': 'кожи', 'flowers': 'цветы', 'cut flowers': 'срезанные цветы', 'oilseeds': 'масличные культуры',
  'apricots': 'абрикосы', 'peaches': 'персики', 'peaches/nectarines': 'персики/нектарины', 'pears': 'груши',
  'plums': 'сливы', 'cherries': 'вишня', 'strawberries': 'клубника', 'blueberries': 'черника',
  'lemons': 'лимоны', 'lemons/limes': 'лимоны/лаймы', 'grapefruit': 'грейпфрут', 'kiwifruit': 'киви',
  'quinoa': 'киноа', 'triticale': 'тритикале', 'buckwheat': 'гречиха', 'mushrooms': 'грибы',
  'mushrooms/truffles': 'грибы/трюфели', 'hops': 'хмель', 'wine': 'вино', 'beer': 'пиво',
  // ---- Отрасли ----
  'mining': 'горнодобывающая промышленность', 'machinery': 'машиностроение', 'textiles': 'текстиль', 'apparel': 'одежда',
  'clothing': 'одежда', 'garments': 'швейные изделия', 'food processing': 'пищевая промышленность', 'food products': 'продукты питания',
  'processed food': 'переработанные продукты', 'chemicals': 'химическая промышленность', 'chemical products': 'химическая продукция',
  'fertilizers': 'удобрения', 'fertilizer': 'удобрения', 'cement': 'цемент', 'electronics': 'электроника',
  'consumer electronics': 'бытовая электроника', 'automobiles': 'автомобили', 'motor vehicles': 'автомобили',
  'cars': 'легковые автомобили', 'vehicles': 'транспортные средства', 'auto parts': 'автозапчасти', 'vehicle parts': 'автозапчасти',
  'shipbuilding': 'судостроение', 'aircraft': 'самолёты', 'aerospace': 'авиакосмическая промышленность',
  'telecommunications': 'телекоммуникации', 'telecommunications equipment': 'телекоммуникационное оборудование',
  'petroleum refining': 'нефтепереработка', 'oil refining': 'нефтепереработка', 'petrochemicals': 'нефтехимия',
  'pharmaceuticals': 'фармацевтика', 'medicaments': 'лекарства', 'packaged medicines': 'фасованные лекарства',
  'tourism': 'туризм', 'banking': 'банковское дело', 'finance': 'финансы', 'financial services': 'финансовые услуги',
  'insurance': 'страхование', 'construction': 'строительство', 'paper': 'бумага', 'paper products': 'бумажная продукция',
  'pulp': 'целлюлоза', 'wood products': 'изделия из дерева', 'wood': 'древесина', 'furniture': 'мебель',
  'toys': 'игрушки', 'footwear': 'обувь', 'shoes': 'обувь', 'leather': 'кожа',
  'leather goods': 'кожаные изделия', 'glass': 'стекло', 'ceramics': 'керамика', 'rubber products': 'резиновые изделия',
  'plastics': 'пластмассы', 'plastic products': 'изделия из пластмасс', 'sugar processing': 'сахарная промышленность',
  'sugar refining': 'сахарная промышленность', 'brewing': 'пивоварение', 'distilling': 'производство спиртного', 'beverages': 'напитки',
  'tobacco products': 'табачные изделия', 'fishing': 'рыболовство', 'fish processing': 'рыбопереработка',
  'forestry': 'лесное хозяйство', 'agriculture': 'сельское хозяйство', 'energy': 'энергетика', 'electricity': 'электроэнергия',
  'software': 'программное обеспечение', 'information technology': 'информационные технологии', 'semiconductors': 'полупроводники',
  'integrated circuits': 'интегральные схемы', 'machine building': 'машиностроение', 'metallurgy': 'металлургия',
  'metals': 'металлы', 'metal products': 'металлоизделия', 'coal mining': 'угледобыча',
  'light industry': 'лёгкая промышленность', 'handicrafts': 'ремёсла', 'carpets': 'ковры',
  'transport equipment': 'транспортное оборудование', 'transportation equipment': 'транспортное оборудование',
  'shipping': 'морские перевозки', 'offshore financial services': 'офшорные финансовые услуги', 'real estate': 'недвижимость',
  'defense products': 'оборонная продукция', 'arms': 'вооружение', 'weapons': 'вооружение', 'satellites': 'спутники',
  'computers': 'компьютеры', 'broadcasting equipment': 'вещательное оборудование', 'office machinery': 'оргтехника',
  'gas turbines': 'газовые турбины', 'ships': 'суда', 'boats': 'лодки', 'trucks': 'грузовики',
  'motorcycles': 'мотоциклы', 'bicycles': 'велосипеды', 'jewelry': 'ювелирные изделия', 'watches': 'часы',
  'precision instruments': 'точные приборы', 'optical instruments': 'оптические приборы',
  'medical equipment': 'медицинское оборудование', 'scientific instruments': 'научные приборы', 'diamonds cutting': 'огранка алмазов',
  'diamond cutting': 'огранка алмазов', 'gas': 'природный газ', 'liquefied natural gas': 'сжиженный природный газ',
  'aluminum products': 'алюминиевые изделия', 'copper products': 'медные изделия', 'gold mining': 'золотодобыча',
  'soap': 'мыло', 'cigarettes': 'сигареты', 'flour': 'мука', 'flour milling': 'мукомольная промышленность',
  'palm kernels': 'пальмовые ядра', 'cotton yarn': 'хлопковая пряжа', 'cotton lint': 'хлопковое волокно',
  'crude oil production': 'добыча нефти', 'oil production': 'добыча нефти',
  'basic petrochemicals': 'базовые нефтехимикаты', 'ammonia': 'аммиак', 'industrial gases': 'промышленные газы',
  'sodium hydroxide (caustic soda)': 'каустическая сода', 'caustic soda': 'каустическая сода',
  'commercial ship repair': 'ремонт торговых судов', 'commercial aircraft repair': 'ремонт гражданских самолётов',
  'natural gas production': 'добыча природного газа', 'phosphate mining': 'добыча фосфатов',
  'aluminum smelting': 'выплавка алюминия', 'copper smelting': 'выплавка меди', 'zinc smelting': 'выплавка цинка',
  'oil refineries': 'нефтеперерабатывающие заводы', 'sawmills': 'лесопилки', 'meat processing': 'мясопереработка',
  'meat packing': 'мясопереработка', 'dairy processing': 'молочная промышленность', 'canning': 'консервирование',
  'wine making': 'виноделие', 'winemaking': 'виноделие', 'olive oil production': 'производство оливкового масла',
}
